EnterpriseDB/repmgr

- autofailover_quick_setup.rst
This is mostly minor cleanups of wording and such.  Details and
motivation (where I was able to come up with something better than
"this sounds more natural" ;) in the commit messages.
> autofailover_quick_setup.rst: Assorted copy edits

- debian/DEBIAN/control
Added postgresql-9.4 to the control file to avoid an installation error.
> Added postgresql-9.4 to debian control file

- SSH-RSYNC.md
Just added two extra spaces for <pre>formatted text. No biggie.
> fix messy formatting

- repmgr.c
- Add display of current node name.
- Add display of upstream node name.
Should close #114
> Add more information in "cluster show"

- repmgr.c
Re-write part of commit from #116 so we have the query as a view to use from the database.
Use the view instead of the query in cluster_show()
> Re-write part of commit from #116 so we have the query as a view to

- repmgr.sql
- sql/repmgr3.0_repmgr3.1.sql
repmgr3.0_repmgr3.1.sql for the upgrade process when passing to 3.1
> We need to update the repmgr.sql file with the new view and create a

- repmgrd.c
repmgrd should terminate if receive position is lower then the replay position
> Fix standby follows other node repmgrd fails

- Makefile
- debian/DEBIAN/control
Added the ability to fetch the installed postgresql version when building the deb package so that install paths are correct.
> Updated makefile for deb creation

- README.md
I think changing /32 -> /24 will make this example better. Since if does not work with /32 ;-)
> Better use /24 network mask in this example

- debian/DEBIAN/control
- repmgr.c
- repmgr.h
Update Debian package to include postgresql-9.5 and have the right version
> Debian auto-build version upgrade

- repmgr.c
success and also on some failures, precisely those when it makes sense
or it is reasonably possible to do so.
> Now STANDBY SWITCHOVER and STANDBY FOLLOW log an event notification on

- doc/install-packages.sgml
Fix package name in documentation.
> Fix package name

- dbutils.c
Fixes memory leaks on witness - #402
> Clear node list to avoid memory leak on witness

- repmgr-action-cluster.c
Fix half of the cluster cleanup help. #459
> Added "cluster cleanup" to help

- repmgr-client.c
Fix the 2nd half of the "cluster cleanup" help. #459
> Fix "cluster cleanup" help

- repmgr.conf.sample
Fixed typo in repmgr.conf.sample, "priority"
> Fixed typo in repmgr.conf.sample, "priority"

- doc/appendix-release-notes.sgml
Signed-off-by: Martín Marqués <martin.marques@2ndquadrant.com>
> Fix typo in the release notes for 4.3

- doc/install-packages.xml
Hi, I think you had a typo, you meant to say Postgres 14 and not 11.  If am wrong just ignore, thanks and take care James Stroud
> Update install-packages.xml postgres 14 and not 11

- doc/configuration-file-optional-settings.xml
We are just cherry-picking some doc fixes to include in the next 5.4 release
> Fix documentation typos

- repmgr-client.c
Definition moved to a different header.
Fixes #856
> PostgreSQL v17 build error

- dbutils.c
- repmgr-action-node.c
- repmgr-action-primary.c
- repmgr-action-standby.c
- repmgrd-physical.c
Since b5934bfd6071 in postgresql.git the flag
`-Wshadow=compatible-local` is activated. This commit fixes any duplicated declaration made in the same function.
References: HL-40
> Fix shadowed declaration

- repmgr.control
> Bump repmgr.control to 5.5

- HISTORY
- doc/appendix-release-notes.xml
- doc/repmgr.xml
> Update HISTORY and appendix for v5.5.0

- doc/install-requirements.xml
- doc/legal.xml
References: https://github.com/EnterpriseDB/repmgr/issues/879
> Update product matrix and copyright date
