EnterpriseDB/repmgr

config.c
if 'node' config parameter is set as a string, nothing complain and all nodes are set to id '0'.
=> One more config check: 'node' 

config.c
With the recent changes, this is the last one to enable repmgr to read the provided example repmgr.conf file, as per #84
=> Ignore comments after values

errcode.h, repmgrd.c
The main change is that now check_connection requires a conninfo
parameter, and the connection object has type (PGconn **) so it can be
replaced by check_connection if needed.
The bug was caused by the fact that the first failure resulted in
*conn == NULL, so that subsequent checks of the upstream connection
were failing irrespectively of the actual state of the upstream node.
Now, when *conn == NULL, check_connection will use conninfo to
establish a new connection and place it into *conn. We introduce a new
INTERNAL_ERROR code for the case when they are both NULL.
In passing, we also reworded a confusing error message, distinguishing
a timeout from the actual elapsed time.
=> Bug #90 fix (autofailover with reconnect_attemps > 1).

README.md, repmgr.c
In some cases it is desirable to remove repmgr's handling of a standby, perhaps
because that standby is to be removed altogether.  With no UNREGISTER command,
one had to manually delete the corresponding row from repl_nodes.
=> Add a STANDBY UNREGISTER command.

debian/repmgr.repmgrd.init
Postgresql under Debian Linux has various wrappers and symlinks, so the final path of the running process differs from the name started. The start-stop-daemon always spawns another repmgrd process without this fix.
=> Debian init script repmgrd process stop fix

repmgrd.c
The patches are so that repmgrd can recover a failed standby server. Now it will not terminate as often as it did, because we want it to keep checking, just in case the standby went down for maintenance for example.
=> Fix failed standby

config.c
For a `char *` variable, `'\0'` is just a strange way to write `NULL`, and clang warns about it.
=> Fix compiler warning

Makefile, debian/DEBIAN/control
* Version set to 3.2dev
* Binaries are placed in PGBINDIR and then linked from /usr/bin,
instead of being placed into /usr/bin directly. This is necessary
for the switchover command, because it requires pg_rewind, which is
placed in PGBINDIR too.
=> Improved "repmgr-auto" Debian package

README.md, config.c, config.h, repmgr.c, repmgr.h
In this branch we add Barman support to `repmgr standby clone`.
Barman will provide both base backups and WAL files. In particular:
- the primary node does not need to perform a new backup every time a new standby is cloned;
- a standby node can be disconnected for longer periods without losing the ability to catch up, and without causing accumulation of WAL files on the primary node;
- the primary node does not require `wal_keep_segments`
- Barman mode cannot be used together with replication slots
=> Barman support

repmgr.c
Certain nodes cloned from Barman backups were missing these subdirectories, and so they were unable to start when promoted.
The problem happened because we fetch the list of files, which currently excludes empty directories, and pull them from the local side, rather than executing remotely `barman recover` to push files.
=> When restoring from Barman, create pg_logical subdirectories

repmgr.c
This should fix the issue, but I haven't tested it yet as I haven't got VMs at hand.
Once it is tested, it can be merged upstream.
---
In order to compute the location of the base backups, we were
retrieving the value of `backup_directory` for the corresponding
Barman server, and then appending `/base`.
This is Barman's default location, but it can be overridden by
specifying an explicit setting of `basebackups_directory`, in which
case repmgr would be unable to remove the prefix from the paths
retrieved from Barman, failing with an error message
Unexpected output from "barman list-files": (...)
As we do not use `backup_directory` anywhere else, the solution is
simple, i.e. retrieve `basebackups_directory` directly.
=> Fixes #312

repmgr-action-node.c
repmgr was printing the name and ID of this node instead of its upstream
Signed-off-by: Tony Finch <dot@dotat.at>
=> "repmgr node status": correct upstream node info

dbutils.c, dbutils.h, repmgr.c
Creates a Postgres checkpoint after `pg_ctl promote` runs on the former standby and before `pg_rewind` runs on the former master. This fixes the race condition that was reported in https://github.com/2ndQuadrant/repmgr/issues/372
=> Create checkpoint after pg_ctl promote

doc/configuration-file-service-commands.sgml
Not a major issue or anything, but I stumbled upon this and thought about fixing it.
=> Missing comma in sudoers example

repmgr-client.c
repmgr-client.c:1895:33: error: ‘TRUE’ undeclared (first use in this function)
if (runtime_options.compact == TRUE)
^
repmgr-client.c:1895:33: note: each undeclared identifier is reported only once for each function it appears in
make: *** [repmgr-client.o] Error 1
=> repmgr-client.c:1895:33: error: ‘TRUE’ undeclared

configure.in
If the required libraries are not installed, all the errors will be caught when gcc is compilling[1] and after `configure` wrapped everything up. I believe we could improve the process just a bit by checking for flex and other required libraries inside this step and before gcc. At least this is what usually happen when someone needs to compile a repo with autotools... tools :-)
Tested with autoconf v2.71. I haven't included the resulting `configure` file because it's going to be a large chunk and not sure if we could bump to that version.
[1] Example of how this looks without flex:
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security …
=> Adding flex and libs as deps

Makefile.global.in, Makefile.in, configdata.c, configfile.h, errcode.h, pgbackupapi.c, pgbackupapi.h, repmgr-action-standby.c, repmgr-client-global.h, repmgr-client.c, repmgr.h
This allows repmgr to use a new model to clone standby nodes: pg_backupapi. If we define those vars in repmgr.conf, then the new mode will be activate:
pg_backupapi_host = 'HOSTNAME'
pg_backupapi_node_name = 'NODE'
pg_backupapi_remote_ssh_command = 'ssh USER@SUPERHOST'
pg_backupapi_backup_id = 'BACKUP_ID'
The new model requires pg-backup-api to be working, which is the REST API we've been working in the last weeks. By default, it's connecting to port TCP/80 but I think we might need to include that as a new option, like `pg_backupapi_port'
=> Connect to pg backup api

pgbackupapi.c, repmgr-action-standby.c, repmgr-action-standby.h
we need to use 7480 instead of 80 by default. And validate the rest of pg-backup-api options when that mode is enabled.
=> Validate repmgr options

doc/cloning-standbys.xml
repmgr v5.4.0 supports this new mode called `pg_backupapi` which is enabled by defining `pg_backupapi_host` in repmgr.conf.
=> Adding new mode to clone standbys.

doc/appendix-release-notes.xml, doc/install-requirements.xml, doc/repmgr.xml
We've done extensive testing of the current version of repmgr against the new version 16 of Postgres. The tests have passed which gives us the green light to add the version as supported in repmgr 5.4.1.
The commit only addresses documentation amendments
=> Adding Postgres version 16 support in 5.4.1

dbutils.c, doc/configuration-permissions.xml, doc/repmgrd-automatic-failover.xml, repmgr.conf.sample
The Repmgr **standby_disconnect_on_failover** option requires to edit permanently (**ALTER SYSTEM** privilege) **wal_retrieve_retry_interval** system parameter, privilege reserved to superusers only until PostgreSQL 14.
From PostgreSQL 15 it is changed, as reported on [v15 changelog](https://www.postgresql.org/docs/release/15.0/):
> Allow [GRANT](https://www.postgresql.org/docs/15/sql-grant.html) to grant permissions to change individual server variables via SET and ALTER SYSTEM (Mark Dilger)
> 
> The new function [has_parameter_privilege()](https://www.postgresql.org/docs/15/functions-info.html) reports on this privilege.
This PR add the check of **wal_retrieve_retry_interval** parameter change privilege via **ALTER SYSTEM** if **repmgr** database user is not a superuser.
=> Added check for wal_retrieve_retry_interval parameter ALTER SYSTEM privilege presence

dbutils.c, dbutils.h, doc/configuration-permissions.xml, doc/repmgr-node-service.xml, doc/repmgr-standby-switchover.xml, repmgr-action-node.c, repmgr-action-standby.c
PostgreSQL 15 introduced pg_checkpoint default role which allows at a non-superuser repmgr database user to perform CHECKPOINT command.
This PR implements what requested in issue #804.
=> Added check for pg_checkpoint role presence

dbutils.c
To work correctly Repmgr database user should be included in some roles ad this is checked by `pg_has_role` function.
In all `pg_has_role` functions `MEMBER` privilege is checked but in Repmgr code no `SET ROLE` is present so it better to check in `pg_has_role` functions `USAGE` privilege instead (that includes `INHERIT` check).
`pg_has_role` function documentation: https://www.postgresql.org/docs/16/functions-info.html#id-1.5.8.32.4.4.2.2.14.1.1.1
PR already discussed with @martinmarques here: https://github.com/EnterpriseDB/repmgr/pull/807#discussion_r1750197750
=> Check for USAGE (instead of MEMBER) privilege in all pg_has_role occurrences

repmgr.conf.sample
This PR fixes some issues in repmgr.conf.sample:
- Added missing "child_nodes_connected_include_witness" parameter
- Fixed "failover_validation_command" parameter description (not updated in PR #651)
- Uniformed spacing in whole file
=> Fixed repmgr.conf.sample

repmgr-action-standby.c
Commit f69485c0 introduced a change in how we check if the repmgr user can run checkpoints on PG15 and newer.
There was a regression in the messages where the conn passed was not declared. That is because the pointer we were using was called checkpoint_conn instead of conn.
=> Fix wrong reference to connection from commit f69485c0
